export const mockPetsData = [
  {
    id: "1",
    name: "Buddy",
    type: "Dog",
    breed: "Golden Retriever",
    age: "3 years",
    ageCategory: "Adult",
    gender: "Male",
    size: "Large",
    location: "San Francisco, CA",
    description:
      "Buddy is a friendly and energetic Golden Retriever who loves playing fetch and going on long walks. He's great with kids and other dogs, making him the perfect family companion. He's house-trained and knows basic commands.",
    image: "/placeholder.svg?height=400&width=400",
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: true,
    ownerId: "owner1",
    status: "available",
    datePosted: "2024-01-15",
  },
  {
    id: "2",
    name: "Luna",
    type: "Cat",
    breed: "Siamese",
    age: "2 years",
    ageCategory: "Adult",
    gender: "Female",
    size: "Medium",
    location: "Los Angeles, CA",
    description:
      "Luna is a beautiful Siamese cat with striking blue eyes. She's independent but affectionate, and loves to curl up in sunny spots. She's perfect for someone looking for a calm, loving companion.",
    image: "/placeholder.svg?height=400&width=400",
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: false,
    ownerId: "owner2",
    status: "available",
    datePosted: "2024-01-20",
  },
  {
    id: "3",
    name: "Max",
    type: "Dog",
    breed: "German Shepherd",
    age: "5 years",
    ageCategory: "Adult",
    gender: "Male",
    size: "Large",
    location: "New York, NY",
    description:
      "Max is a loyal and intelligent German Shepherd. He's well-trained and would make an excellent guard dog. He needs an experienced owner who can provide him with plenty of exercise and mental stimulation.",
    image: "/placeholder.svg?height=400&width=400",
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: true,
    ownerId: "owner1",
    status: "available",
    datePosted: "2024-01-10",
  },
  {
    id: "4",
    name: "Bella",
    type: "Cat",
    breed: "Persian",
    age: "4 years",
    ageCategory: "Adult",
    gender: "Female",
    size: "Medium",
    location: "Chicago, IL",
    description:
      "Bella is a gentle Persian cat with a luxurious coat. She enjoys quiet environments and gentle petting. She would be perfect for someone looking for a calm, indoor companion.",
    image: "/placeholder.svg?height=400&width=400",
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: false,
    goodWithPets: false,
    ownerId: "owner3",
    status: "available",
    datePosted: "2024-01-25",
  },
  {
    id: "5",
    name: "Charlie",
    type: "Rabbit",
    breed: "Holland Lop",
    age: "1 year",
    ageCategory: "Adult",
    gender: "Male",
    size: "Small",
    location: "Seattle, WA",
    description:
      "Charlie is an adorable Holland Lop rabbit with floppy ears. He's litter-trained and loves to hop around and explore. He would make a great pet for families with children.",
    image: "/placeholder.svg?height=400&width=400",
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: true,
    ownerId: "owner2",
    status: "available",
    datePosted: "2024-02-01",
  },
  {
    id: "6",
    name: "Rocky",
    type: "Dog",
    breed: "Bulldog",
    age: "6 months",
    ageCategory: "Puppy",
    gender: "Male",
    size: "Medium",
    location: "Miami, FL",
    description:
      "Rocky is a playful Bulldog puppy who loves attention and playtime. He's still learning basic commands but is very eager to please. He would thrive in a loving home with patience for training.",
    image: "/placeholder.svg?height=400&width=400",
    vaccinated: true,
    spayedNeutered: false,
    goodWithKids: true,
    goodWithPets: true,
    ownerId: "owner1",
    status: "available",
    datePosted: "2024-02-05",
  },
]

export const mockOwnerPets = [
  {
    id: "1",
    name: "Buddy",
    type: "Dog",
    breed: "Golden Retriever",
    age: "3 years",
    image: "./images/buddy.jpeg",
    status: "available",
    datePosted: "2024-01-15",
  },
  {
    id: "3",
    name: "Max",
    type: "Dog",
    breed: "German Shepherd",
    age: "5 years",
    image: "./images/max.jpeg",
    status: "available",
    datePosted: "2024-01-10",
  },
  {
    id: "6",
    name: "Rocky",
    type: "Dog",
    breed: "Bulldog",
    age: "6 months",
    image: "./images/rocky.jpeg",
    status: "available",
    datePosted: "2024-02-05",
  },
]

export const mockAdoptionRequests = [
  {
    id: "1",
    petId: "1",
    petName: "Buddy",
    adopterName: "Sarah Johnson",
    adopterEmail: "sarah.johnson@email.com",
    adopterPhone: "(555) 123-4567",
    message:
      "Hi! I'm very interested in adopting Buddy. I have a large backyard and two kids who would love to have a dog. I've had Golden Retrievers before and understand their needs. Would love to meet him!",
    date: "2024-02-10",
    status: "pending",
  },
  {
    id: "2",
    petId: "3",
    petName: "Max",
    adopterName: "Mike Chen",
    adopterEmail: "mike.chen@email.com",
    adopterPhone: "(555) 987-6543",
    message:
      "I'm interested in adopting Max. I'm an experienced dog owner and have had German Shepherds before. I live alone and work from home, so I can provide plenty of attention and exercise.",
    date: "2024-02-08",
    status: "approved",
  },
  {
    id: "3",
    petId: "6",
    petName: "Rocky",
    adopterName: "Emily Davis",
    adopterEmail: "emily.davis@email.com",
    adopterPhone: "(555) 456-7890",
    message:
      "Rocky looks adorable! I'm looking for a puppy to train and grow up with. I have experience with bulldogs and understand their specific needs. I'd love to schedule a meet and greet.",
    date: "2024-02-12",
    status: "pending",
  },
]

export const mockAdopterRequests = [
  {
    id: "1",
    petId: "2",
    petName: "Luna",
    ownerName: "Jennifer Smith",
    ownerContact: "jennifer.smith@email.com",
    message:
      "I'm interested in adopting Luna. I live in a quiet apartment and am looking for a calm, affectionate cat companion. I work from home and can provide lots of attention.",
    date: "2024-02-09",
    status: "pending",
  },
  {
    id: "2",
    petId: "4",
    petName: "Bella",
    ownerName: "Robert Wilson",
    ownerContact: "robert.wilson@email.com",
    message:
      "Bella seems like the perfect cat for me. I'm retired and looking for a gentle, quiet companion. I have experience with Persian cats and understand their grooming needs.",
    date: "2024-02-07",
    status: "approved",
  },
  {
    id: "3",
    petId: "5",
    petName: "Charlie",
    ownerName: "Lisa Anderson",
    ownerContact: "lisa.anderson@email.com",
    message:
      "I'd love to adopt Charlie! I have a large indoor space and experience with rabbits. My daughter has been asking for a pet rabbit for months and Charlie looks perfect.",
    date: "2024-02-11",
    status: "pending",
  },
]

export const mockFavoritePets = [
  {
    id: "2",
    name: "Luna",
    type: "Cat",
    breed: "Siamese",
    age: "2 years",
    description:
      "Luna is a beautiful Siamese cat with striking blue eyes. She's independent but affectionate, and loves to curl up in sunny spots.",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "4",
    name: "Bella",
    type: "Cat",
    breed: "Persian",
    age: "4 years",
    description:
      "Bella is a gentle Persian cat with a luxurious coat. She enjoys quiet environments and gentle petting.",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "5",
    name: "Charlie",
    type: "Rabbit",
    breed: "Holland Lop",
    age: "1 year",
    description:
      "Charlie is an adorable Holland Lop rabbit with floppy ears. He's litter-trained and loves to hop around and explore.",
    image: "/placeholder.svg?height=400&width=400",
  },
]
